# Generated by Django 2.0.4 on 2018-07-07 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('msg_id', models.IntegerField(default=48, primary_key=True, serialize=False, unique=True)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(default='noname')),
                ('subject', models.TextField(default='no topic')),
                ('message', models.TextField(default='no message')),
                ('date', models.DateTimeField(verbose_name=datetime.date(2018, 7, 7))),
            ],
        ),
    ]
